os:
  - linux
  - osx
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bc
      - g++-4.8
env:
  matrix:
    - TRAVIS_NODE_VERSION="18"
    - TRAVIS_NODE_VERSION="18.18.2"
    - TRAVIS_NODE_VERSION="19"
    - TRAVIS_NODE_VERSION="20"
    - TRAVIS_NODE_VERSION="lts/*" ELECTRON_VERSION="25.1.1"
matrix:
  exclude:
    - os: osx
      env: TRAVIS_NODE_VERSION="18.18.2"
    - env: TRAVIS_NODE_VERSION="17"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - if [[ $TRAVIS_NODE_VERSION == "0.8" ]]; then npm config set strict-ssl false; fi
  - if [[ -z "$ELECTRON_VERSION" && $(echo "$TRAVIS_NODE_VERSION < 4" | bc -l)  == "1" ]]; then npm install npm@2 && mv node_modules npm && npm/.bin/npm --version && npm/.bin/npm install; else npm --version && npm install; fi
  - if [[ -z "$ELECTRON_VERSION" ]]; then node_modules/.bin/node-gyp rebuild --directory test; else node_modules/.bin/node-gyp rebuild --target=v$ELECTRON_VERSION --dist-url=https://atom.io/download/electron --directory test; fi
script:
  - if [[ -z "$ELECTRON_VERSION" && $TRAVIS_NODE_VERSION != "17" ]]; then node_modules/.bin/tap --gc test/js/*-test.js; fi