# http://www.appveyor.com/docs/appveyor-yml

image:
  - Visual Studio 2017

# Test against these versions of Io.js and Node.js.
environment:
  matrix:
  # node.js
    - nodejs_version: "18"
    - nodejs_version: "19"
    - nodejs_version: "20"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
  - IF %nodejs_version% LSS 4 npm -g install npm@2
  - IF %nodejs_version% EQU 5 npm -g install npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  # Typical npm stuff.
  - npm install
  - IF %nodejs_version% LSS 8 (npm run rebuild-tests) ELSE (npm run rebuild-tests-2017)

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - IF %nodejs_version% LSS 1 (npm test) ELSE (IF %nodejs_version% LSS 4 (iojs node_modules\tap\bin\tap.js --gc test/js/*-test.js) ELSE (node node_modules\tap\bin\tap.js --gc test/js/*-test.js))

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
